
version: 2
jobs:
  cypress/build:
    resource_class: xlarge
    docker:
    - image: cimg/node:16.15
    steps:
    - checkout
    - restore_cache:
        keys:
        - cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
    - run:
        name: Npm CI
        command: npm ci && npx browserslist@latest --update-db
    - save_cache:
        key: cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
        paths:
        - ~/.npm
        - ~/.cache
    # - run: npm run lint
    - persist_to_workspace:
        root: ~/
        paths:
        - project
        - .cache/Cypress
  cypress/e2e-tests:
    docker:
    - image: cypress/browsers:node16.13.2-chrome100-ff98
    parallelism: 5
    steps:
    - attach_workspace:
        at: ~/
    - run:
        command: npx cypress verify
    - run:
        name: before tests
        command: circleci tests glob "tests/e2e/*/*.js" | circleci tests split > circleci.tests && sed -i 's/No timing found for "//g' circleci.tests && sed -i 's/"//g' circleci.tests && grep "\S" circleci.tests > uno.txt && mv uno.txt circleci.tests && cat circleci.tests
    - run: mkdir tests/e2e/metrics
    - run:
        name: run tests
        command: |
          node .circleci/gh_pull_request.js
          export GH_COMMENT_URL=$(node .circleci/gh_pull_request.js)
          echo $GH_COMMENT_URL
          TZ=UTC npx vue-cli-service test:e2e --mode test --headless --browser chrome --spec $(cat circleci.tests | tr "\n" ",")
    - run:
        name: preparate coverage
        command: mkdir coverage-test && mv .nyc_output/out.json coverage-test/coverage-$CIRCLE_NODE_INDEX-$(date +"%s%N").json
    - save_cache:
        paths:
          - coverage-test/
        key: pm-{{ .Environment.CIRCLE_NODE_INDEX }}-{{ .Branch }}-{{ .Environment.CIRCLE_WORKFLOW_ID }}-coverage.json
    - run: ls -la coverage-test
    - store_artifacts:
        path: tests/e2e/screenshots
    - store_artifacts:
        path: tests/e2e/metrics
  cypress/report:
    docker:
    - image: cimg/node:16.15
    steps:
      - attach_workspace:
          at: ~/
      # - run:
      #     name: tests unit
      #     command: npm test
      - run: mkdir coverage-test
      - restore_cache:
          keys:
            - pm-0-{{ .Branch }}-{{ .Environment.CIRCLE_WORKFLOW_ID }}-coverage.json
      - restore_cache:
          keys:
            - pm-1-{{ .Branch }}-{{ .Environment.CIRCLE_WORKFLOW_ID }}-coverage.json
      - restore_cache:
          keys:
            - pm-2-{{ .Branch }}-{{ .Environment.CIRCLE_WORKFLOW_ID }}-coverage.json
      - restore_cache:
          keys:
            - pm-3-{{ .Branch }}-{{ .Environment.CIRCLE_WORKFLOW_ID }}-coverage.json
      - restore_cache:
          keys:
            - pm-4-{{ .Branch }}-{{ .Environment.CIRCLE_WORKFLOW_ID }}-coverage.json

      - run: npx nyc merge coverage-test && mkdir .nyc_output
      - run: mv coverage.json .nyc_output/out.json
      - run: npx nyc report --reporter html --reporter text --reporter json-summary --report-dir combined-coverage
      - store_artifacts:
          path: combined-coverage
      # - store_test_results:
      #     path: test_summary_reports

workflows:
  build:
    jobs:
    - cypress/build
    - cypress/e2e-tests:
        requires:
          - cypress/build
    - cypress/report:
        requires:
          - cypress/e2e-tests

  version: 2
